### ISSUE TITLE
Migrate from SDL 1.2 to SDL 2.0

### ISSUE THREAD

**Issue by takenu** [BasFaggingerAuer/tiny-game-engine#19]
A couple of years ago SDL 2.0 was released, and it improves upon SDL 1.2 in various ways that are important for modern applications. Examples include video and keyboard handling.

Tiny-game-engine should move to SDL 2.0 as well. The [migration guide](https://wiki.libsdl.org/MigrationGuide) should help in making the necessary adjustments.

**Comment by BasFaggingerAuer** [comment]
You are completely right. Let me see if I can get this to work.

**Comment by BasFaggingerAuer** [comment]
"U vraagt, wij draaien." That seems to work (see latest commit). Please let me know if you run into any problems.

**Comment by takenu** [comment]
Wow, that was fast... :O
