### ISSUE TITLE
Cannot remap or disable 'Esc', 'F1' keys

### ISSUE THREAD

**Issue by takenu** [BasFaggingerAuer/tiny-game-engine#2]
Currently there is no way to change the mapping of 'Esc' for exiting. Similarly 'F1' cannot be unbound from switching to wireframe and back. Adjustments should be made to the tiny::os::SDLApplication class to allow handling _all_ keys in a way defined by the user.

I suggest this is done via a flag 'useDefaultSignals' or so, which can be set to 'false' by the user to disable them. Additionally, functionality must be added to tiny::os::SDLApplication to allow exiting (and optionally wireframe switching) by calling a function rather than by pressing a key.

**Comment by BasFaggingerAuer** [comment]
Added support for custom callbacks in commit e66a9c5eeced940f0b32261be26bb4d593953d77. See SDLApplication::keyDownCallback().
